name: Swift

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: swift test
