name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  format-lint:
    runs-on: macos-14

    steps:
    - name: Install tools
      run: brew install swiftformat
      
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check format
      run: swiftformat . --lint

  test:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: swift test
