name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  format-lint:
    runs-on: macos-14

    steps:
    - name: Install tools
      run: brew install swiftformat
      
    - name: Checkout maplibre-swiftui-dsl-playground
      uses: actions/checkout@v3

    - name: Check format
      run: swiftformat . --lint

  test:
    runs-on: macos-14
    strategy:
      matrix:
        scheme: [
          MapLibreSwiftUI-Package
        ]
        destination: [
          # TODO: Add more destinations
          'platform=iOS Simulator,name=iPhone 15,OS=17.2'
        ]

    steps:
    - name: Install tools
      run: brew install xcbeautify

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'

    - name: Checkout maplibre-swiftui-dsl-playground
      uses: actions/checkout@v3

    - name: Test ${{ matrix.scheme }} on ${{ matrix.destination }}
      run: xcodebuild -scheme ${{ matrix.scheme }} test -skipMacroValidation -destination '${{ matrix.destination }}' | xcbeautify && exit ${PIPESTATUS[0]}
